In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('Downloads\password_data.csv',error_bad_lines=False)

Skipping line 2810: expected 2 fields, saw 5
Skipping line 4641: expected 2 fields, saw 5
Skipping line 7171: expected 2 fields, saw 5
Skipping line 11220: expected 2 fields, saw 5
Skipping line 13809: expected 2 fields, saw 5
Skipping line 14132: expected 2 fields, saw 5
Skipping line 14293: expected 2 fields, saw 5
Skipping line 14865: expected 2 fields, saw 5
Skipping line 17419: expected 2 fields, saw 5
Skipping line 22801: expected 2 fields, saw 5
Skipping line 25001: expected 2 fields, saw 5
Skipping line 26603: expected 2 fields, saw 5
Skipping line 26742: expected 2 fields, saw 5
Skipping line 29702: expected 2 fields, saw 5
Skipping line 32767: expected 2 fields, saw 5
Skipping line 32878: expected 2 fields, saw 5
Skipping line 35643: expected 2 fields, saw 5
Skipping line 36550: expected 2 fields, saw 5
Skipping line 38732: expected 2 fields, saw 5
Skipping line 40567: expected 2 fields, saw 5
Skipping line 40576: expected 2 fields, saw 5
Skipping line 41864: expected 2 field

Skipping line 525174: expected 2 fields, saw 5
Skipping line 526251: expected 2 fields, saw 5
Skipping line 529611: expected 2 fields, saw 5
Skipping line 531398: expected 2 fields, saw 5
Skipping line 534146: expected 2 fields, saw 5
Skipping line 544954: expected 2 fields, saw 5
Skipping line 553002: expected 2 fields, saw 5
Skipping line 553883: expected 2 fields, saw 5
Skipping line 553887: expected 2 fields, saw 5
Skipping line 553915: expected 2 fields, saw 5
Skipping line 554172: expected 2 fields, saw 5
Skipping line 563534: expected 2 fields, saw 5
Skipping line 565191: expected 2 fields, saw 5
Skipping line 574108: expected 2 fields, saw 5
Skipping line 574412: expected 2 fields, saw 5
Skipping line 575985: expected 2 fields, saw 5
Skipping line 580091: expected 2 fields, saw 5
Skipping line 582682: expected 2 fields, saw 5
Skipping line 585885: expected 2 fields, saw 5
Skipping line 590171: expected 2 fields, saw 5
Skipping line 591924: expected 2 fields, saw 5
Skipping line

In [3]:
data

password  strength
0           kzde5577         1
1           kino3434         1
2          visi7k1yr         1
3           megzy123         1
4        lamborghin1         1
...              ...       ...
669635    10redtux10         1
669636     infrared1         1
669637  184520socram         1
669638     marken22a         1
669639      fxx4pw4g         1

[669640 rows x 2 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 669640 entries, 0 to 669639
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   password  669639 non-null  object
 1   strength  669640 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 10.2+ MB


In [5]:
data['strength'].unique()

array([1, 2, 0], dtype=int64)

In [6]:
data['strength'].value_counts()

1    496801
0     89702
2     83137
Name: strength, dtype: int64

In [7]:
data.isna().sum()

password    1
strength    0
dtype: int64

In [8]:
data.dropna(inplace=True)

In [9]:
data

password  strength
0           kzde5577         1
1           kino3434         1
2          visi7k1yr         1
3           megzy123         1
4        lamborghin1         1
...              ...       ...
669635    10redtux10         1
669636     infrared1         1
669637  184520socram         1
669638     marken22a         1
669639      fxx4pw4g         1

[669639 rows x 2 columns]

# Separating independent & dependent variable

# Shuffling the data for robustness of the ML model

In [10]:
data_tuples=np.array(data)

In [11]:
data_tuples

array([['kzde5577', 1],
       ['kino3434', 1],
       ['visi7k1yr', 1],
       ...,
       ['184520socram', 1],
       ['marken22a', 1],
       ['fxx4pw4g', 1]], dtype=object)

In [12]:
import random
random.shuffle(data_tuples)

In [13]:
X = [i[0] for i in data_tuples]

In [14]:
X

['kzde5577',
 'kino3434',
 'kzde5577',
 'visi7k1yr',
 'megzy123',
 'lamborghin1',
 'visi7k1yr',
 'visi7k1yr',
 'AVYq1lDE4MgAZfNt',
 'u6c8vhow',
 'v1118714',
 'megzy123',
 'megzy123',
 'u6c8vhow',
 'WUt9IZzE0OQ7PkNE',
 'jerusalem393',
 '612035180tok',
 'v1118714',
 'WUt9IZzE0OQ7PkNE',
 'v1118714',
 'g067057895',
 'megzy123',
 'kzde5577',
 '52558000aaa',
 '52558000aaa',
 'faranumar91',
 'elyass15@ajilent-ci',
 'elyass15@ajilent-ci',
 'AVYq1lDE4MgAZfNt',
 'asv5o9yu',
 'gaymaids1',
 'schalke04',
 'as326159',
 'jerusalem393',
 'gaymaids1',
 'as326159',
 'prisonbreak1',
 'lamborghin1',
 'megzy123',
 '52558000aaa',
 'prisonbreak1',
 'jerusalem393',
 'pHyqueDIyNQ8vmhb',
 '0169395484a',
 'yqugu927',
 'lsdlsd1',
 'alimagik1',
 'intel1',
 'sbl571017',
 'TyWM72UNEex8Q8Y',
 'trabajonet9',
 'v1118714',
 'tamanagung6',
 'AVYq1lDE4MgAZfNt',
 'exitos2009',
 'klara-tershina3H',
 'ok>bdk',
 'elyass15@ajilent-ci',
 'prisonbreak1',
 'WUt9IZzE0OQ7PkNE',
 'khmer100.03278&?><Mnb',
 'kzde5577',
 'czuodhj972',


In [15]:
y = [i[1] for i in data_tuples]

In [16]:
y

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 0,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 0,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 2,
 1,
 1,
 2,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 2,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 0,
 2,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 2,
 1,
 2,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


# Dividing the list into characters

In [17]:
def dividing(input):
    characters=[]
    for i in input:
        characters.append(i)
    return characters

In [18]:
dividing(X[0])

['k', 'z', 'd', 'e', '5', '5', '7', '7']

# Tf-idf for vectorizing the characters

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [20]:
vectorizer = TfidfVectorizer(tokenizer=dividing)

In [21]:
x = vectorizer.fit_transform(X)

In [22]:
x

<669639x133 sparse matrix of type '<class 'numpy.float64'>'
	with 5646465 stored elements in Compressed Sparse Row format>

In [23]:
x.shape

(669639, 133)

In [24]:
vectorizer.get_feature_names_out()

array(['\x02', '\x04', '\x05', '\x06', '\x08', '\x0e', '\x0f', '\x10',
       '\x11', '\x12', '\x13', '\x16', '\x17', '\x19', '\x1b', '\x1c',
       '\x1d', '\x1e', ' ', '!', '"', '#', '$', '%', '&', '(', ')', '*',
       '+', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8',
       '9', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`',
       'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
       'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
       '{', '|', '}', '~', '\x7f', '\x81', '\x8d', '¡', '¦', '«', '°',
       '±', '²', '³', '´', 'µ', '¶', '·', '¹', 'º', '¾', '¿', 'ß', 'à',
       'á', 'â', 'ä', 'å', 'æ', 'ç', 'é', 'ê', 'í', 'ï', 'ð', 'ñ', 'ò',
       'ó', 'ô', 'õ', 'ö', '÷', 'ù', 'ú', 'û', 'ü', 'ý', 'þ', 'ÿ', '—',
       '‚', '›', '™'], dtype=object)

In [26]:
first_document_vector =x[0]

In [34]:
first_document_vector

<1x133 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [35]:
first_document_vector.T.todense()

matrix([[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.56745191],
        [0.        ],
        [0.59210098],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0

In [36]:
df=pd.DataFrame(first_document_vector.T.todense(),index=vectorizer.get_feature_names_out(),columns=['Tf-idf'])

In [37]:
df.sort_values('Tf-idf',ascending=False)

Tf-idf
7   0.592101
5   0.567452
z   0.335358
k   0.291348
d   0.285135
..       ...
6   0.000000
4   0.000000
3   0.000000
2   0.000000
™   0.000000

[133 rows x 1 columns]

# Applying ML algorithm Logistic Regression

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2) #20% will be used as testing data

In [33]:
X_train.shape

(535711, 133)

In [38]:
from sklearn.linear_model import LogisticRegression

In [39]:
classification = LogisticRegression(random_state=0,multi_class='multinomial').fit(X_train,y_train) #multinomial as there are three categories 0,1,2

# Checking a random password strength

In [41]:
password = np.array(['awsd45gff^&@#d'])
pred = vectorizer.transform(password)
classification.predict(pred)

array([2])

In [42]:
y_pred = classification.predict(X_test)

In [43]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

# Checking the accuracy of the model

In [47]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [48]:
cm = confusion_matrix(y_test,y_pred)

In [49]:
print(cm)

[[ 5393 12495    12]
 [ 3938 92842  2608]
 [   43  5194 11403]]


In [50]:
print(accuracy_score(y_test,y_pred))

0.8186338928379427


In [51]:
from sklearn.metrics import classification_report

In [52]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.58      0.30      0.40     17900
           1       0.84      0.93      0.88     99388
           2       0.81      0.69      0.74     16640

    accuracy                           0.82    133928
   macro avg       0.74      0.64      0.67    133928
weighted avg       0.80      0.82      0.80    133928

